package com.myspace.gobear;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TravelInsuranceRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Duration")
	private int duration;
	@org.kie.api.definition.type.Label("Total Premium")
	private double totalPremium;
	@org.kie.api.definition.type.Label("Standard Premium")
	private double standardPremium;
	@org.kie.api.definition.type.Label("Additional Premium")
	private double additionalPremium;
	@org.kie.api.definition.type.Label("Location")
	private java.lang.String location;
	@org.kie.api.definition.type.Label("Family Package")
	private boolean family;
	@org.kie.api.definition.type.Label("Additional Week")
	private int additionalWeek;

	@org.kie.api.definition.type.Label("Start Date")
	private java.util.Date startDate;

	@org.kie.api.definition.type.Label("End Date")
	private java.util.Date endDate;

	public TravelInsuranceRequest() {
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public double getTotalPremium() {
		return this.totalPremium;
	}

	public void setTotalPremium(double totalPremium) {
		this.totalPremium = totalPremium;
	}

	public double getStandardPremium() {
		return this.standardPremium;
	}

	public void setStandardPremium(double standardPremium) {
		this.standardPremium = standardPremium;
	}

	public double getAdditionalPremium() {
		return this.additionalPremium;
	}

	public void setAdditionalPremium(double additionalPremium) {
		this.additionalPremium = additionalPremium;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public boolean isFamily() {
		return this.family;
	}

	public void setFamily(boolean family) {
		this.family = family;
	}

	public int getAdditionalWeek() {
		return this.additionalWeek;
	}

	public void setAdditionalWeek(int additionalWeek) {
		this.additionalWeek = additionalWeek;
	}

	public java.util.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.util.Date startDate) {
		this.startDate = startDate;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public TravelInsuranceRequest(int duration, double totalPremium,
			double standardPremium, double additionalPremium,
			java.lang.String location, boolean family, int additionalWeek,
			java.util.Date startDate, java.util.Date endDate) {
		this.duration = duration;
		this.totalPremium = totalPremium;
		this.standardPremium = standardPremium;
		this.additionalPremium = additionalPremium;
		this.location = location;
		this.family = family;
		this.additionalWeek = additionalWeek;
		this.startDate = startDate;
		this.endDate = endDate;
	}

}