kind: Template
apiVersion: v1
metadata:
  annotations:
    description: The Gogs NodePort for SSH
    tags: gogs,nodeport
  name: ${APPLICATION_NAME}
objects:
- kind: Service
  metadata:
    annotations:
      description: The Gogs Server's SSH port
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ssh
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: 1025-tcp
      port: 1025
      protocol: TCP
      targetPort: 1025
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: gogs  