apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-console
  name: task-console
spec:
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: task-console
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-console
    version: 1.12.0
  name: task-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-console
  template:
    metadata:
      labels:
        app: task-console
        version: 1.12.0
    spec:
      containers:
      - env:
        - name: KOGITO_DATAINDEX_HTTP_URL
          value: http://dataindex:8080/graphql
        - name: KOGITO_TASK_CONSOLE_PROPS
          value: -Dkogito.consoles.keycloak.config.url=http://keycloak:8080/auth -Dkogito.consoles.keycloak.config.health-check-url=http://keycloak:8080/auth/realms/kogito/.well-known/openid-configuration
        image: quay.io/kiegroup/kogito-task-console:1.12.0
        imagePullPolicy: IfNotPresent
        name: task-console
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
  test: false